### ISSUE TITLE
v0.2.2 -> v0.2.3 broke compatibility

### ISSUE THREAD

**Issue by scottlamb** [webrtc-rs/rtcp#9]
This code compiles without warnings and works correctly on v0.2.2. It doesn't build with v0.2.3.

```
   Compiling retina v0.0.5 (/home/slamb/git/retina)
warning: unused import: `rtcp::packet::Packet`
   --> src/client/rtp.rs:189:13
    |
189 |         use rtcp::packet::Packet;
    |             ^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(unused_imports)]` on by default

error[E0599]: no function or associated item named `unmarshal` found for struct `Header` in the current scope
   --> src/client/rtp.rs:193:49
    |
193 |             let h = match rtcp::header::Header::unmarshal(&data) {
    |                                                 ^^^^^^^^^ function or associated item not found in `Header`
    |
    = help: items from traits can only be used if the trait is in scope
    = note: the following trait is implemented but not in scope; perhaps add a `use` for it:
            `use webrtc_util::marshal::Unmarshal;`

error[E0599]: no function or associated item named `unmarshal` found for struct `rtcp::sender_report::SenderReport` in the current scope
   --> src/client/rtp.rs:211:66
    |
211 |                     let pkt = rtcp::sender_report::SenderReport::unmarshal(&pkt)
    |                                                                  ^^^^^^^^^ function or associated item not found in `rtcp::sender_report::SenderReport`
    |
    = help: items from traits can only be used if the trait is in scope
    = note: the following trait is implemented but not in scope; perhaps add a `use` for it:
            `use webrtc_util::marshal::Unmarshal;`

error: aborting due to 2 previous errors; 1 warning emitted

For more information about this error, try `rustc --explain E0599`.
error: could not compile `retina`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by rainliu** [comment]
Sorry for this inconvenience caused by v0.2.3+ upgrade.

To work around this incompatibility issue, please use 
`rtp = "=0.2.2"`
in your Cargo.toml.

since v0.2.4, RTP crate is refactored for error handling with thiserror + anyhow. I apologized for not upgrading it to v0.3.x.

**Comment by scottlamb** [comment]
Thanks. I'll work around; just wasn't sure if you were aware.
